post http://localhost:3002/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJpZ3lhIiwiaWQiOiI1ZTFlMDk1M2FhNWQ1ODIwNzE5YWEzODAiLCJpYXQiOjE1NzkxMTA0MTh9.StzSAsHdWh-RsoCJJYy9hzNibB489RfYEG0XIjUxTdI

{
    "title": "Wuttt",
    "author": "Bigya",
    "url": "uuuoo.com",
    "likes":134
}